--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Itzdvbravo/BravoClan
build-by-default: true
branches:
- master
projects:
  BravoClan:
    path: ""
    icon: "new.png"
    #Credit to DevRqzor for the phpstan thing
    lint:
      phpstan: false
...
